# Customer Churn Analysis and Prediction

Project Overview:
The project aims to analyze customer churn in a telecommunications company and developpredictive models to identify at-risk customers. The ultimate goal is to provide actionable insights and recommendations to reduce churn and improve customer retention.

# Tasks 1:Data Cleaning and Preprocessing

Description:
1.Handle missing values in the dataset.
2.Convert categorical variables into numerical representations using techniques like one-hot encoding.

Skills:
1.Proficiency in data cleaning techniques.
2.Knowledge of missing data handling methods.
3.Familiarity with encoding categorical variables.

# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import sklearn

# Loading DataSet

In [2]:
data=pd.read_csv("Customer_Churn_analysis.csv")
data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

# 1.Handle missing values in the dataset.

In [3]:
# Identify missing values
missing_values = data.isnull().sum()
missing_values

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [4]:
# Save cleaned data
data.to_csv("Customer_Churn_analysis.csv", index=False)

# 2.Convert categorical variables into numerical representations using techniques like one-hot encoding.

In [5]:
# Identify categorical variables
categorical_cols = ['gender','MultipleLines', 'InternetService','Contract','PaymentMethod']

In [6]:
# Apply one-hot encoding
data_encoded = pd.get_dummies(data, columns=categorical_cols)
data_encoded

,customerID,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,...,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,0,Yes,No,1,No,No,Yes,No,No,...,True,False,False,True,False,False,False,False,True,False
1,5575-GNVDE,0,No,No,34,Yes,Yes,No,Yes,No,...,True,False,False,False,True,False,False,False,False,True
2,3668-QPYBK,0,No,No,2,Yes,Yes,Yes,No,No,...,True,False,False,True,False,False,False,False,False,True
3,7795-CFOCW,0,No,No,45,No,Yes,No,Yes,Yes,...,True,False,False,False,True,False,True,False,False,False
4,9237-HQITU,0,No,No,2,Yes,No,No,No,No,...,False,True,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,Yes,Yes,24,Yes,Yes,No,Yes,Yes,...,True,False,False,False,True,False,False,False,False,True
7039,2234-XADUH,0,Yes,Yes,72,Yes,No,Yes,Yes,No,...,False,True,False,False,True,False,False,True,False,False
7040,4801-JZAZL,0,Yes,Yes,11,No,Yes,No,No,No,...,True,False,False,True,False,False,False,False,True,False
7041,8361-LTMKD,1,Yes,No,4,Yes,No,No,No,No,...,False,True,False,True,False,False,False,False,False,True
7042,3186-AJIEK,0,No,No,66,Yes,Yes,No,Yes,Yes,...,False,True,False,False,False,True,True,False,False,False

In [7]:
# Save encoded data
data_encoded.to_csv("encoded_dataset.csv", index=False)